#!/bin/sh
# description: configure script for djatoka-richmond package

#Get directory pointer to djatoka-richmond and assign in ../scripts/tomcat
echo
echo "Enter the absolute location of djatoka-richmond's parent directory... [/usr/share]"
read DIR
if [[ $DIR != '' ]]; then
	echo "DIR is $DIR"
	`sed -i "s|DIR=\/usr\/share|DIR=$DIR|g" tomcat`
else
	DIR=/usr/share
	echo "DIR = $DIR"
fi

#Adjust tomcat's runlevels for chkconfig and /etc/init.d
echo "Enter the runlevels tomcat should use... [234]"
read RUNLEVELS
if [[ $RUNLEVELS != '' ]]; then
	echo "RUNLEVELS are $RUNLEVELS"
	`sed -i "s|234|$RUNLEVELS|" tomcat`
else
	RUNLEVELS=234
	echo "RUNLEVELS = $RUNLEVELS"
fi

#Get tomcat ports and assign in ../apache-tomcat/conf/server.xml
echo
echo "Enter the HTTP port tomcat should use... [8080]"
read PORT1
if [[ $PORT1 != '' ]]; then
	echo "HTTP port = $PORT1"
	`sed -i "s|8080|$PORT1|g" ../apache-tomcat/conf/server.xml`
else
	PORT1=8080
	echo "HTTP port = $PORT1"
fi

echo
echo "Enter the HTTP redirect port tomcat should use... -i [8443]"
read PORT2
if [[ $PORT2 != '' ]]; then
	echo "HTTP redirect port = $PORT2"
	`sed -i "s|8443|$PORT2|g" ../apache-tomcat/conf/server.xml`
else
	PORT2=8443
	echo "HTTP redirect port = $PORT2"
fi

echo
echo "Enter the AJP port tomcat should use... [8009]"
read PORT3
if [[ $PORT3 != '' ]]; then
	echo "AJP port = $PORT3"
	`sed -i "s|8009|$PORT3|g" ../apache-tomcat/conf/server.xml`
else
	PORT3=8009
	echo "AJP port = $PORT3"
fi

#Get public address of server and assign to server
#in ../apache-tomcat/webapps/djatoka/viewer.html
echo
echo "Enter the public address of the djatoka server... [localhost]"
read server
if [[ $server != '' ]]; then
	echo "public address is $SERVER"
	`sed -i "s|localhost:8080|$SERVER:$PORT1|g" ../apache-tomcat/webapps/djatoka/viewer.html`
else
	SERVER=localhost
	echo "public address is $SERVER"
fi

#copy ../scripts/tomcat to /etc/init.d and register with chkconfig
echo
echo "Copying tomcat to /etc/init.d/"
`cp tomcat /etc/init.d`
`cd /etc/init.d`
echo
echo "Registering tomcat with chkconfig"
`chkconfig --add "tomcat"`
