#!/bin/sh
# description: Tomcat Start Stop Restart
# processname: tomcat
# chkconfig: 234 20 80
DIR=/usr/share
export DIR
CATALINA_HOME=$DIR/djatoka-richmond/apache-tomcat
export CATALINA_HOME
DJATOKA_HOME=$DIR/djatoka-richmond/adore-djatoka
export DJATOKA_HOME

LIBPATH=$DJATOKA_HOME/lib

if [ `uname` = 'Linux' ] ; then
  if [ `uname -p` = "x86_64" ] ; then
    # Assume Linux AMD 64 has 64-bit Java
    PLATFORM="Linux-x86-64"
  else
    # 32-bit Java
    PLATFORM="Linux-x86-32"
  fi
fi

LD_LIBRARY_PATH="$LIBPATH/$PLATFORM"
export LD_LIBRARY_PATH

KAKADU_LIBRARY_PATH="-DLD_LIBRARY_PATH=$LIBPATH/$PLATFORM"
KAKADU_HOME=$DJATOKA_HOME/bin/$PLATFORM
export KAKADU_HOME

cd $DJATOKA_HOME/bin
for line in `ls -l $LIBPATH | grep '.jar'`
	do
	classpath="$classpath:$LIBPATH/$line"
done

CLASSPATH=.:../build/:$classpath
JAVA_OPTS="$DEBUG -Djava.awt.headless=true -Xmx512M -Xms64M -Dkakadu.home=$KAKADU_HOME -Djava.library.path=$LIBPATH/$PLATFORM $KAKADU_LIBRARY_PATH"
export JAVA_OPTS

case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
esac
exit 0
